name: Build Waterfox Remote
on:
  workflow_dispatch: # Cho phép bạn kích hoạt thủ công từ iPhone

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Python and Build Tools
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'


      - name: Compile Waterfox
        run: |
          ./mach bootstrap --application-choice=browser 
          ./mach build

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v-biui_selected-linux"
          name: "Firefox Linux v-biui_selected"
          body: "Automated custom-branded Firefox Linux build compiled via iPhone 17 Pro Max."
          draft: false
          prerelease: false
          files: firefox-biui_selected-linux-x64.tar.gz
